apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "authelia.fullname" . }}-config
  labels:
    {{- include "authelia.labels" . | nindent 4 }}
data:
  configuration.yml: |
    server:
      address: tcp://0.0.0.0:9091

    log:
      level: info

    identity_validation:
      reset_password:
        jwt_secret: {{ .Values.authelia.jwtSecret | quote }}

    session:
      name: authelia_session
      same_site: lax
      expiration: 1h
      inactivity: 5m
      cookies:
        - name: authelia_session
          domain: {{ .Values.authelia.sessionDomain }}
          authelia_url: http://{{ .Values.authelia.sessionDomain }}:9091

    authentication_backend:
      file:
        path: /config/users_database.yml

    access_control:
      default_policy: one_factor
      rules:
        - domain: "*"
          policy: one_factor

    storage:
      encryption_key: {{ .Values.authelia.jwtSecret | quote }}
      local:
        path: /config/db.sqlite3

    notifier:
      filesystem:
        filename: /config/notification.txt

  users_database.yml: |
    users:
      {{ .Values.authelia.adminUsername }}:
        displayname: Administrator
        password: "{{ .Values.authelia.adminPassword }}"
        email: admin@localhost
        groups:
          - admins
